apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genesis
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: workload
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: workload/genesis
    repoURL: https://github.com/mcandeia/control-plane-desired-state
    targetRevision: HEAD
